@echo off
echo Matando todos los procesos Python...
taskkill /F /IM python.exe /T 2>nul

echo Esperando 3 segundos...
timeout /t 3 /nobreak >nul

echo Limpiando cache de Python...
for /d /r . %%d in (__pycache__) do @if exist "%%d" rd /s /q "%%d"
del /s /q *.pyc 2>nul

echo Esperando 2 segundos...
timeout /t 2 /nobreak >nul

echo Iniciando servidor...
python run.py
